from models import deit
from models import tnt
from models import pvt
from models import t2t_vit
from models import localvit
from models import localvit_tnt
from models import localvit_pvt
from models import localvit_t2t
from models import swin_transformer
from models import localvit_swin